name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master

      - name: âš™ï¸ Setup Node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: ğŸ“¦ Cache Node modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: â• Install Node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: ğŸ”¨ Generate static project
        run: yarn run generate

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master

      - name: âš™ï¸ Setup Node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: ğŸ“¦ Cache Node modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: â• Install Node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: âœ… Run tests
        run: yarn test

  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@master

      - name: âš™ï¸ Setup Node environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: ğŸ“¦ Cache Node modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: â• Install Node modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: ğŸš¨ Run linter
        run: yarn lint
